/// Parses the "high"/"medium"/"low" strings written by the ingestion
/// pipeline (see src/database/supabase_client.py::_consensus_for). Neutral
/// factual buckets only — the UI must not attach editorial language like
/// "widely covered" or "ignored by media" to these.
enum Consensus { high, medium, low }

extension ConsensusLabel on Consensus {
  String get label {
    switch (this) {
      case Consensus.high:
        return 'High consensus';
      case Consensus.medium:
        return 'Medium consensus';
      case Consensus.low:
        return 'Low consensus';
    }
  }
}

Consensus consensusFromJson(String value) {
  switch (value) {
    case 'high':
      return Consensus.high;
    case 'medium':
      return Consensus.medium;
    case 'low':
    default:
      return Consensus.low;
  }
}

class OutletSource {
  final String outletName;
  final String outletUrl;
  final DateTime? publishTime;

  /// From the curated outlet_credibility table only (see migration 0006) —
  /// never generated by the AI pipeline. Null if the outlet has no curated
  /// third-party score.
  final double? outletCredibilityScore;

  const OutletSource({
    required this.outletName,
    required this.outletUrl,
    this.publishTime,
    this.outletCredibilityScore,
  });

  factory OutletSource.fromJson(Map<String, dynamic> json) {
    return OutletSource(
      outletName: json['outlet_name'] as String,
      outletUrl: json['outlet_url'] as String,
      publishTime: json['publish_time'] == null
          ? null
          : DateTime.parse(json['publish_time'] as String),
      outletCredibilityScore: (json['outlet_credibility_score'] as num?)?.toDouble(),
    );
  }
}

class CoverageAnalysis {
  final int totalOutlets;
  final List<String> outletsList;
  final Consensus consensus;

  const CoverageAnalysis({
    required this.totalOutlets,
    required this.outletsList,
    required this.consensus,
  });

  factory CoverageAnalysis.fromJson(Map<String, dynamic> json) {
    return CoverageAnalysis(
      totalOutlets: json['total_outlets'] as int,
      outletsList: (json['outlets_list'] as List<dynamic>? ?? [])
          .map((e) => e as String)
          .toList(),
      consensus: consensusFromJson(json['consensus'] as String),
    );
  }
}
