-- Migration 0006: source tracking, coverage analysis, and a legally-safe
-- claim-level fact-check layer (fact_checks_v2).
--
-- These extend the existing fact_checks / crisis_reports rows rather than
-- introducing a parallel "news_headlines" pipeline: outlet_sources and
-- coverage_analysis attach to whichever row a raw item was deduped into
-- (exactly one of fact_check_id / crisis_report_id is set), and
-- fact_checks_v2 is a 1:1 extension of a fact_checks row.
--
-- Run this in the Supabase SQL editor after 0002-0005.

-- ---------------------------------------------------------------------------
-- Outlet credibility: manually curated, third-party only. Never populated by
-- the AI pipeline or by our own editorial judgment — see
-- src/database/outlet_credibility.py, which only ever reads this table and
-- never writes a score it invented. Rows are added by a human citing a named
-- external index (e.g. Press Council of India, a named Media Trust Index
-- report); outlets with no cited score simply have no row here, and
-- outlet_sources.outlet_credibility_score is left NULL rather than guessed.
-- ---------------------------------------------------------------------------

create table if not exists outlet_credibility (
    outlet_name text primary key,
    credibility_score float not null check (credibility_score between 0 and 100),
    source_index text not null,
    source_url text,
    last_updated date not null default current_date
);

comment on table outlet_credibility is
    'Manually curated outlet credibility scores, each citing a named third-party index. Never generated by the AI pipeline.';

-- ---------------------------------------------------------------------------
-- outlet_sources: every outlet that covered a given fact_checks / crisis_reports
-- row. Complements the existing fact_checks.sources / crisis_reports.evidence_items
-- jsonb arrays (which are evidence for the claim itself) by additionally
-- tracking outlet_credibility_score for coverage/consensus analysis.
-- ---------------------------------------------------------------------------

create table if not exists outlet_sources (
    id uuid primary key default gen_random_uuid(),
    fact_check_id uuid references fact_checks(id) on delete cascade,
    crisis_report_id uuid references crisis_reports(id) on delete cascade,
    outlet_name text not null,
    outlet_url text not null,
    publish_time timestamptz,
    -- Snapshotted from outlet_credibility at insert time; NULL if the outlet
    -- has no curated third-party score. Never computed by the AI pipeline.
    outlet_credibility_score float,
    created_at timestamptz not null default now(),
    check (
        (fact_check_id is not null and crisis_report_id is null)
        or (fact_check_id is null and crisis_report_id is not null)
    ),
    unique (fact_check_id, outlet_url),
    unique (crisis_report_id, outlet_url)
);

create index if not exists outlet_sources_fact_check_idx on outlet_sources (fact_check_id);
create index if not exists outlet_sources_crisis_report_idx on outlet_sources (crisis_report_id);
create index if not exists outlet_sources_outlet_name_idx on outlet_sources (outlet_name);

-- ---------------------------------------------------------------------------
-- coverage_analysis: one row per fact_checks / crisis_reports row, recomputed
-- (upserted) whenever outlet_sources changes for that item. consensus is a
-- neutral factual bucket only (high/medium/low outlet count) — the Flutter
-- UI must not attach editorial language ("widely covered", "ignored") to it.
-- ---------------------------------------------------------------------------

create table if not exists coverage_analysis (
    id uuid primary key default gen_random_uuid(),
    fact_check_id uuid references fact_checks(id) on delete cascade,
    crisis_report_id uuid references crisis_reports(id) on delete cascade,
    total_outlets integer not null default 0,
    outlets_list text[] not null default '{}',
    consensus text not null check (consensus in ('high', 'medium', 'low')),
    created_at timestamptz not null default now(),
    check (
        (fact_check_id is not null and crisis_report_id is null)
        or (fact_check_id is null and crisis_report_id is not null)
    ),
    unique (fact_check_id),
    unique (crisis_report_id)
);

-- ---------------------------------------------------------------------------
-- fact_checks_v2: 1:1 legally-safe claim-level extension of a fact_checks row.
-- status vocabulary (VERIFIED/DISPUTED/NEEDS_MORE_INFO) is intentionally
-- distinct from fact_checks.status (VERIFIED/FALSE/MISLEADING/...) — this
-- layer never accuses an outlet, only cites official sources. See the system
-- prompt in src/ai_processor/groq_processor.py (process_claim_v2) for the
-- legal constraints this schema backs.
-- ---------------------------------------------------------------------------

create table if not exists fact_checks_v2 (
    id uuid primary key default gen_random_uuid(),
    fact_check_id uuid not null unique references fact_checks(id) on delete cascade,
    claim text not null,
    status text not null check (status in ('VERIFIED', 'DISPUTED', 'NEEDS_MORE_INFO')),
    evidence jsonb not null default '[]',
    verdict text not null,
    confidence float not null check (confidence between 0 and 1),
    perspectives jsonb,
    created_at timestamptz not null default now()
);

create index if not exists fact_checks_v2_fact_check_idx on fact_checks_v2 (fact_check_id);

-- ---------------------------------------------------------------------------
-- RLS: same pattern as schema.sql — anon (app) key gets read-only access,
-- the pipeline writes with the service-role key which bypasses RLS entirely.
-- outlet_credibility is also public-read since the UI cites it directly
-- ("Source: Press Council of India").
-- ---------------------------------------------------------------------------

alter table outlet_credibility enable row level security;
alter table outlet_sources enable row level security;
alter table coverage_analysis enable row level security;
alter table fact_checks_v2 enable row level security;

create policy "Public read access" on outlet_credibility for select using (true);
create policy "Public read access" on outlet_sources for select using (true);
create policy "Public read access" on coverage_analysis for select using (true);
create policy "Public read access" on fact_checks_v2 for select using (true);
